config/routes.rb
Kms::Application.routes.draw do

  resources :notifications do
    member do
      get 'feed'
    end
  end
  resources :tags


  get "article_attachments/download"

  resources :domains do
    member do
      get 'list_folders'
    end
  end


  get "pages/home"
  root :to => 'pages#home'

  resources :user_sessions, as: :user_sessions
  resources :users, as: :users do
    member do
      get 'vcard'
      put 'retire'
      put 'revoke_retirement'
    end
  end
  resources :articles do
    member do
      post 'publish'
      post 'send_for_approval'
      post 'unpublish'
      post 'reject'
      post 'refactor'
      post 'like'
    end
  end
    
  #secure file downloads
  match "/uploads/:id/:basename.:extension", :controller => "article_attachments", :action => "download", :conditions => { :method => :get }
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :content, :subject, :active
  validates :subject, :length => { :maximum => 50 }
  validates :content, :length => { :maximum => 200 }
  scope :last_updated, order('updated_at desc')
  scope :active, where(active: true)
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  load_and_authorize_resource
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  def feed
    @notifications = Notification.active
  end
end

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject %>
    <%= f.input :content, input_html: {rows: '5'} %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Back', notifications_path, class: "btn" %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>
<hr>

<%= render 'form' %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>
<hr>
<%= link_to 'New Notification', new_notification_path, class: "btn btn-primary" %>
<hr>
<table class="table table-bordered" id="datatables">
  <thead>
    <th>Subject</th>
    <th>Content</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.subject %></td>
        <td><%= notification.content %></td>
        <td><%= notification.active ? 'Active' : 'Inactive' %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notifications/new.html.erb
<h1>New notification</h1>
<hr>
<%= render 'form' %>

app/views/notifications/show.html.erb
<div class="offset2 span8">
  <p>
  <b>Subject:</b>
  <%= @notification.subject %>
  </p>

  <p>
  <b>Content:</b>
  <%= @notification.content %>
  </p>

  <div class="form-actions">
    <%= link_to 'Edit', edit_notification_path(@notification), class: "btn" %>
    <%= link_to 'Back', notifications_path, class: "btn" %>
  </div>
</div>