config/routes.rb
Kms::Application.routes.draw do

  resources :notifications do
    member do
      get 'feed'
    end
  end
  resources :tags


  get "article_attachments/download"

  resources :domains do
    member do
      get 'list_folders'
    end
  end


  get "pages/home"
  root :to => 'pages#home'

  resources :user_sessions, as: :user_sessions
  resources :users, as: :users do
    member do
      get 'vcard'
      put 'retire'
      put 'revoke_retirement'
    end
  end
  resources :articles do
    member do
      post 'publish'
      post 'send_for_approval'
      post 'unpublish'
      post 'reject'
      post 'refactor'
      post 'like'
    end
  end
    
  #secure file downloads
  match "/uploads/:id/:basename.:extension", :controller => "article_attachments", :action => "download", :conditions => { :method => :get }
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  username         :string(255)      not null
#  email            :string(255)
#  crypted_password :string(255)
#  salt             :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  role             :string(255)
#  domain           :string(255)
#  about_me         :text
#  designation      :string(255)
#  avatar           :string(255)
#  mobile           :integer
#  state            :string(255)
#

require 'file_size_validator' 
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  acts_as_voter

  attr_accessor :password_not_required
  attr_accessible :username, :email, :password, :password_confirmation, :role, :about_me, :designation, :skills_attributes, :interests_attributes, :avatar, :state, :mobile, :upload_limit, :domain_id, :date_of_birth, :remove_avatar
  validates_length_of :password, :minimum => 5, :message => "password must be at least 5 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
  validates_uniqueness_of :email, case_sensitive: false
  validates_presence_of :username, :email, :domain_id, :role
  validates_presence_of :password, :unless => :password_not_required
  validate :dob_validation

  has_many :articles
  has_many :skills
  has_many :interests
  belongs_to :domain

  accepts_nested_attributes_for :skills, :allow_destroy => true,  :reject_if => proc { |attributes| attributes['skill_name'].blank? }
  accepts_nested_attributes_for :interests, :allow_destroy => true,  :reject_if => proc { |attributes| attributes['interest_name'].blank? }

  mount_uploader :avatar, AvatarUploader
  validates :avatar, 
    :file_size => { 
    :maximum => 1.megabytes.to_i 
  } 

  before_validation :strip_whitespaces

  include PgSearch
  pg_search_scope :search, against: [[:username, 'A'], [:domain, 'A'], [:email, 'B'], [:designation, 'B'], [:state, 'B']],
    using: {
      tsearch: {
        dictionary: "english",
        prefix: true,
      }
    },
    associated_against: {
      skills: {:skill_name => 'B'},
    }

  def self.roles
    [:contributor, :coordinator, :admin, :domain_head]
  end

  def admin?
    role == 'admin'
  end

  def list_of_interests
    interests.pluck(:interest_name).join(", ")
  end

  def list_of_skills
    skills.pluck(:skill_name).join(", ")
  end

  def published_articles
    articles.where(aasm_state: 'published')
  end

  def draft_articles
    articles.where(aasm_state: 'draft')
  end

  def approval_pending
    articles.where(aasm_state: 'approval_pending')
  end

  def rejected_articles
    articles.where(aasm_state: 'rejected')
  end

  def km_coordinator_pending_approvals
    Article.includes(:domain).
      km_coordinator_pending_approvals(self)
  end

  def strip_whitespaces
    self.username = self.username.strip
    self.email = self.email.strip
  end

  def self.text_search(query)
    if query.present?
      search(query)
    else
      scoped.order('username asc')
    end
  end

  def self.active
    where("retire is not true")
  end

  def retire!
    update_attribute(:retire, true)
  end

  def revoke_retirement!
    update_attribute(:retire, false)
  end

  def retired?
    retire
  end

  def user_upload_limit
    @upload_limit ||= calculate_upload_limit
  end

  def calculate_upload_limit
    if upload_limit.to_f > 0.0
      the_upload_limit = self.upload_limit.to_f
    else
      the_upload_limit = 10
    end
  end

  private
  def dob_validation
    if self.date_of_birth
      dob = self.date_of_birth.to_date
      if (dob + 18.years) > Date.today
        errors.add :date_of_birth, "You need to be atleast 18 years old. Kindly enter a valid date of birth."
      elsif ((Date.today - dob)/365).to_i > 100
        errors.add :date_of_birth, "Are you really over a 100 years old? Kindly enter a valid date of birth."
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    list_of_users = User.includes(:domain).text_search(params[:search])
    unless current_user.admin?
      list_of_users = list_of_users.active
    end
    @users = list_of_users.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @domains = Domain.list_domains

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def vcard
    @user = User.find params[:id]
  end

  # GET /users/new
  # GET /users/new.json
  def new
    unless current_user.admin?
      redirect_to user_path(current_user), alert: "Not Authorized"
      return
    end
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @user.date_of_birth = @user.date_of_birth.strftime("%d/%m/%Y") if @user.date_of_birth
    unless current_user.admin? or current_user == @user
      redirect_to user_path(current_user), alert: "Not Authorized"
      return
    end
  end

  # POST /users
  # POST /users.json
  def create
    unless current_user.admin?
      redirect_to user_path(current_user), alert: "Not Authorized"
      return
    end

    @user = User.new(params[:user])
    if @user.save
      redirect_to user_path(current_user), notice: "Account has been created."
    else
      render action: "new" 
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    unless current_user.admin?
      params[:user].delete :role
      params[:user].delete :domain
    end


    @user = User.find(params[:id])
    if params[:user][:password].blank?
      params[:user].delete :password
      params[:user].delete :password_confirmation
      @user.password_not_required = true
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def retire
    @user = User.find params[:id]
    if @user.retire!
      redirect_to users_path, notice: "The user was retired"
    else
      redirect_to users_path, alert: "The user could not be retired"
    end
  end

  def revoke_retirement
    @user = User.find params[:id]
    if @user.revoke_retirement!
      redirect_to users_path, notice: "The user's retirement was revoked"
    else
      redirect_to users_path, alert: "The user's retirement could not be revoked"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def render_avatar user, size
    return image_tag(user.avatar.url(:nail).to_s, class: "img-circle") if size == "nail"
    image_tag(user.avatar.url(size.to_sym).to_s, class: "img-polaroid")
  end

  def stats user
    draft = content_tag('div') do
      content_tag('h4', "Drafts") +
      content_tag('h1', 
        link_to(user.draft_articles.count, articles_path(state: 'draft'), remote: true, class: "ajax_page"))
    end

    pending = content_tag('div') do
      content_tag('h4', "Pending") +
      content_tag('h1', 
        link_to(user.approval_pending.count, articles_path(state: 'approval_pending'), remote: true, class: "ajax_page"))
    end

    published = content_tag('div') do
      content_tag('h4', "Published") +
      content_tag('h1', 
        link_to(user.published_articles.count, articles_path(state: 'published'), remote: true, class: "ajax_page"))
    end

    rejected = content_tag('div') do
      content_tag('h4', "Re-Work") +
      content_tag('h1', 
        link_to(user.rejected_articles.count, articles_path(state: 'rejected'), remote: true, class: "ajax_page"))
    end

    return draft + "<hr>".html_safe + pending + "<hr>".html_safe  + published + "<hr>".html_safe + rejected + "<hr>".html_safe 
  end

end

app/views/users/_avatar.html.erb
<%= link_to(render_avatar(user, size), vcard_user_path(user)) %>
<br>
<% if user == current_user && size != "nail" -%>
  <small><b><%= link_to 'Edit Profile', edit_user_path(current_user), class: "muted" %></b></small>
<% end -%>

app/views/users/_display_km_pending_approvals_count.html.erb
<%- if current_user.admin? or current_user.role == 'coordinator' %>
  <h4>Action Items</h4>
  <h1><%= link_to current_user.km_coordinator_pending_approvals.count,
    articles_path(km_pending: true), remote: true, class: "ajax_page" %></h1>
  <hr>
<% end -%>

app/views/users/_form.html.erb
<%= simple_nested_form_for(@user, url: user_path(@user), method: :put) do |f| %>
  <%= f.error_notification %>

  <div class="row-fluid">
    <div class="form-inputs">
      <div class="fluid-row">
        <%= f.input :username, label: 'Name' %>
        <%= f.input :email %>
        <%= f.input :designation %>
        <%= f.input :mobile %>
        <%= f.input :date_of_birth, as: :string, label: "Date of birth", input_html: { class: "dateofbirth" } %>
        <%= f.input :state, label: "Location" %>
        <%= f.input :avatar, as: :file, label: "Profile Picture", hint: "Size of the picture should not exceed 1 Mb" %>
        <%= f.input :remove_avatar, as: :boolean %>
        <% if current_user.admin? -%>
          <%= f.input :role, collection: User.roles %>
          <%= f.input :domain_id, collection: Domain.list_domains, value_method: :id, label_method: :domain_name %>
          <%= f.input :upload_limit %>
        <% end -%>
        <%= f.input :about_me, input_html: {rows: 4} %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
        <%= f.link_to_add ' Add Skill', :skills, class: "btn btn-primary icon-plus"%><br><br>
        <%= f.link_to_add ' Add Interest', :interests, class: "btn btn-primary icon-plus"%><br><br>
      </div>
      <div class="row-fluid skills">
        <%= f.simple_fields_for :skills do |a| -%>
          <div class="span4 well" style="margin-right: 10px">
            <strong class="muted">Skill</strong>
            <%= a.input_field :skill_name, placeholder: "Skill" %><br>
            <%= a.link_to_remove ' remove', class: 'icon-remove badge'%>
          </div>
        <% end -%>
      </div>
      <div class="row-fluid interests">
        <%= f.simple_fields_for :interests do |a| -%>
          <div class="span4 well" style="margin-right: 10px">
            <strong class="muted">Interest</strong>
            <%= a.input_field :interest_name, placeholder: "Interest" %><br>
            <%= a.link_to_remove ' remove', class: 'icon-remove badge'%>
          </div>
        <% end -%>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
      <%= link_to 'Back', user_path(@user), class: "btn" %>
    </div>
  </div>
<% end %>

app/views/users/_leaderboard_for_domains.html.erb
<table class="table table-bordered">
  <thead>
    <th><h4>Folders</h4></th>
  </thead>
  <tbody>
  <tr><td style="background: #f3f3f3"><%= article_folder_path domain %></td></tr>
    <% domains.each do |domain| -%>
      <% cache domain do -%>
        <tr>
          <td><%= link_to " #{domain.domain_name}", articles_path(domain_id: domain.id), remote: true, class: "ajax_page icon-folder-close icon-large" %></td>
        </tr>
      <% end -%>
    <% end -%>
    <% if domains.empty? -%>
      <tr><td class="muted">No sub-folders available</td></tr>
    <% end -%>
  </tbody>
</table>

app/views/users/_search_bar.html.erb
<div class='row-fluid'>
  <%= form_tag articles_path, :method => :get, class: "form-inline", remote: true do %>
    <%= text_field_tag :search, nil, class: "block-level-input span10", placeholder: "Search Articles by subject, folder, tags, files, content or author.." %>
    <%= button_tag "<i class='icon-search'></i> Search".html_safe, class: "btn search_btn ajax_page" %>
    <div class="domain_id">
    </div>
  <% end -%>
</div>

app/views/users/_user_menu.html.erb
<%= render 'display_km_pending_approvals_count' %>
<% cache current_user do -%>
  <%= stats current_user %>
<% end -%>

app/views/users/_vcard.html.erb
<div class="span12">
  <div class="row-fluid">
    <div class='span3 center' style="">
      <div class="row-fluid">
        <%= render 'avatar', user: user, size: 'large' -%>
      </div>
      <div class="row-fluid">
        <hr>
        <h2 class="muted">Contributed <%= pluralize user.published_articles.count, "article" %></h2>
      </div>
    </div>
    <div class='span9'>
      <h1><%= user.username.camelcase %> <small class="muted"><b>(<%= user.email %>)</b></small></h1>
      <hr>
      <div class="row-fluid">
        <div class="span6">
          <h4>Domain: <%= user.domain.domain_name %></h4>
          <h4>Designation: <%= user.designation %></h4>
          <h4>Skills: <small><b><%= user.list_of_skills %></b></small></h4>
        </div>
        <div class="span6">
          <h4>Location: <%= user.state %></h4>
          <h4>Mobile: <%= user.mobile %></h4>
          <h4>Interests: <small><b><%= user.list_of_interests %></b></small></h4>
        </div>
      </div>
      <div class="row-fluid">
        <hr>
        <h4>About Me</h4>
        <p><%= user.about_me -%></p>
      </div>
    </div>
  </div>
</div>

app/views/users/_welcome_message.html.erb
<% if @domain -%>
  <%= welcome_message @domain %>
<% end -%>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<hr>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Employee Lookup</h1>
<hr>
<% if current_user.admin? -%>
  <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
<hr>
<% end -%>
<div class="span2 pull-right center" style="font-size: 120%"><b>Total:</b> <%= @users.count %></div>
<div class="search-bar">
  <%= form_tag users_path, method: :get, class: "form-search" do %>
    <%= text_field_tag :search, nil, placeholder: "Search Employees by name, email, domain, designation or skill sets", class: "span6" %>
    <%= submit_tag 'Search', class: "btn" %>
  <% end -%>
</div>

<table class="table table-bordered" id="">
  <thead>
    <th>Name</th>
    <th>Email</th>
    <th>Domain</th>
    <th>Designation</th>
    <th>Location</th>
    <th>Skills</th>
    <th>DOB</th>
    <% if current_user.admin? -%>
      <th>Role</th>
      <th>Last Login</th>
      <th>Last Activity</th>
      <th>Status</th>
      <th>Retire!</th>
      <th></th>
      <th></th>
    <% end -%>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, vcard_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.domain.domain_name %></td>
        <td><%= user.designation %></td>
        <td><%= user.state %></td>
        <td><%= truncate(user.list_of_skills, size: 50) %></td>
        <td><%= user.date_of_birth ? user.date_of_birth.to_s(:short) : "N/A" %></td>
        <% if current_user.admin? -%>
          <td><%= user.role %></td>
          <td><%= time_ago_in_words user.last_login_at rescue "N/A" %></td>
          <td><%= time_ago_in_words user.last_activity_at rescue "N/A" %></td>
          <td><%= user.retired? ? "Retired" : "Active" -%></td>
          <% if user.retired? -%>
            <td><%= link_to 'Revoke Retirement', revoke_retirement_user_path(user), method: :put, class: "btn btn-success btn-mini" %></td>
          <% else -%>
            <td><%= link_to 'Retire', retire_user_path(user), method: :put, class: "btn btn-danger btn-mini" %></td>
          <% end -%>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
  
<%= will_paginate @users -%>
</table>

app/views/users/new.html.erb
<h1>New User</h1>
<hr>

<%= simple_form_for(@user, url: users_path(@user)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username, label: 'Name' %>
    <%= f.input :email %>
    <%= f.input :role, collection: User.roles %>
    <%= f.input :domain_id, collection: Domain.list_domains, value_method: :id, label_method: :domain_name %>
    <%= f.input :designation %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to 'Back', root_path, class: "btn" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row-fluid">
  <div class="span2 profile-stats">
    <%= render 'avatar', user: current_user, size: 'prof' %>
    <hr>
    <div class="leaderboard">
      <%= render 'leaderboard_for_domains', domain: @domain, domains: @domains %>
    </div>
  </div>
  <div class="span8 search-and-feed">
    <%= render 'search_bar' %>
    <hr>
    <div class="row-fluid">
      <div class="welcome_message">
      </div>
      <div class="feed" data-articles_path="<%= articles_path %>">
        <%# render 'articles/search_results' %>
      </div>
    </div>
  </div>
  <div class="span2 create">
    <%= link_to '<i class="icon-pencil"></i> Article'.html_safe, new_article_path, class: "btn btn-block btn-large btn-primary" %>
    <hr>
    <div class="">
      <div class="center">
        <%= render 'user_menu' %>
      </div>
    </div>
  </div>
</div>

app/views/users/vcard.html.erb
<%= render 'vcard', user: @user %>