config/routes.rb
Kms::Application.routes.draw do

  resources :notifications do
    member do
      get 'feed'
    end
  end
  resources :tags


  get "article_attachments/download"

  resources :domains do
    member do
      get 'list_folders'
    end
  end


  get "pages/home"
  root :to => 'pages#home'

  resources :user_sessions, as: :user_sessions
  resources :users, as: :users do
    member do
      get 'vcard'
      put 'retire'
      put 'revoke_retirement'
    end
  end
  resources :articles do
    member do
      post 'publish'
      post 'send_for_approval'
      post 'unpublish'
      post 'reject'
      post 'refactor'
      post 'like'
    end
  end
    
  #secure file downloads
  match "/uploads/:id/:basename.:extension", :controller => "article_attachments", :action => "download", :conditions => { :method => :get }
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  tag_name   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
  attr_accessible :tag_name

  has_many :articles, through: :article_tags
  validates_presence_of :tag_name
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :tag_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Back', tags_path, class: "btn" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Manage Tags</h1>
<hr>
<%= link_to 'New Tag', new_tag_path, class: "btn btn-primary" %>
<hr>

<table class="table" id="datatables">
  <thead>
    <th>Tag name</th>
    <th></th>
  </thead>

<% @tags.each do |tag| %>
  <tbody>
    <tr>
      <td><%= tag.tag_name %></td>
      <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    </tr>
  <tbody>
<% end %>
</table>

<br />

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tag name:</b>
  <%= @tag.tag_name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>