config/routes.rb
Kms::Application.routes.draw do

  resources :notifications do
    member do
      get 'feed'
    end
  end
  resources :tags


  get "article_attachments/download"

  resources :domains do
    member do
      get 'list_folders'
    end
  end


  get "pages/home"
  root :to => 'pages#home'

  resources :user_sessions, as: :user_sessions
  resources :users, as: :users do
    member do
      get 'vcard'
      put 'retire'
      put 'revoke_retirement'
    end
  end
  resources :articles do
    member do
      post 'publish'
      post 'send_for_approval'
      post 'unpublish'
      post 'reject'
      post 'refactor'
      post 'like'
    end
  end
    
  #secure file downloads
  match "/uploads/:id/:basename.:extension", :controller => "article_attachments", :action => "download", :conditions => { :method => :get }
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
end

app/views/layouts/_display_notification.html.erb
    <% if current_user && notifications.any? %>
      <div class="row-fluid">
        <ul id="notifications_feed" class="js-hidden span12">
        <% notifications.each do |notification| -%>
          <li class="news-item"><a href="#"><%= notification.content %></a></li>
        <% end -%>
        </ul>
      </div>
    <% end %>

app/views/layouts/_footer.html.erb
<hr>
<div class="row-fluid">
  <div class="span4">
    <%= image_tag 'ftl.png', width: '160', height: '200', align: 'left'  %>
  </div>
  <div class="span4 center">
    &copy; 2013 Forbes Technosys Ltd.
  </div>
  <div class="span4">
    <%= image_tag 'sp.png', width: '100', height: '40', align: 'right'  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FtLASH" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <% if current_user -%>
            <% link = user_path(current_user) -%>
          <% else -%>
            <% link = root_path -%>
          <% end -%>
          <a class="brand" href="<%= link %>"><%= image_tag "flash.png", width: '80', height: '45' %></a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <% if current_user -%>
                <% if current_user.admin? -%>
                  <li class="divider-vertical"></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     <i class="icon-cogs"></i> Administration
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Manage Users", users_path %></li>
                      <li><%= link_to "Manage Domains", domains_path %></li>
                      <li><%= link_to "Manage Tags", tags_path %></li>
                      <li><%= link_to "Manage Notifications", notifications_path %></li>
                    </ul>
                  </li>
                <% end -%>
                <li class="divider-vertical"></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                   <i class="icon-user"></i> <%= current_user.username  %>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
                    <li><%= link_to "Your VCard", vcard_user_path(current_user.id) %></li>
                    <li><%= link_to "Employee Lookup", users_path %></li>
                    <li class="divider"></li>
                    <li> <%= link_to "Logout", :logout %></li>
                  </ul>
                </li>
              <% else -%>
            </ul>
                <%= form_tag user_sessions_path, :method => :post, class: "navbar-search pull-right" do %>
                      <%= text_field_tag :email, nil, class: "input-medium", placeholder: "Email", autofocus: true %>
                      <%= password_field_tag :password, nil, class: "input-medium", placeholder: "Password"  %>
                      <%= submit_tag "Login", class: "btn btn-primary" %>
                <% end %>
              <% end -%>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <%= render 'layouts/display_notification', notifications: @notifications %>

    <div class="container">
      <div class="row">
        <div class="span12">
          <br><br><br>
          <div class="row-fluid">
            <% flash.each do |name, msg| %>
              <% unless msg.blank? -%>
              <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                <a class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
              </div>
              <% end %>
            <% end -%>
          </div><!--/row-fluid-->
          
          <div class="row-fluid">
            <%= yield %>
          </div><!--/row-->

          <footer>
            <%= render 'layouts/footer' %>
          </footer>

        </div>
      </div>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>